### ISSUE TITLE
Improvement to make it production-ready

### ISSUE THREAD

**Issue by andrielfn** [spencerdcarlson/google-certs#3]
Hey @spencerdcarlson,

I've tested the `google_cets` in a large project together with Joken and it worked really well in development, however, there are a few things that are blocking me to make my implementation ready-for-production:

- there is no test coverage, which is a blocker for us considering that `google_certs` would be an important piece in our system – do you have any plans to add tests in the short-term?
- the path (`/priv`) where the certificate is stored is hardcoded, so when testing our code it stores the file outside the `/test` folder, which is not good;
- the `https://www.googleapis.com` is also hardcoded, so it's not possible to stub this call in the tests;

I believe I could work on some of these and send a PR afterward. What do you think?

**Comment by spencerdcarlson** [comment]
@andrielfn thanks for the feedback. It be great if you wanted to add some test. What do you think about this PR - https://github.com/spencerdcarlson/google-certs/pull/4 to address the other issues.
